services:
    patty:
        build: .
        volumes:
            - ./credentials.ini:/app/credentials.ini
            - ./src:/app/src
            - ./data:/app/data
            - ./out:/app/out
        user: "1051"
        environment:
            - CREDENTIALS_FILE=/app/credentials.ini
            - PRIVATE_CACHE=/app/data
            - OUTPUTS_PATH=/app/out
        command: "start"
